services:
  # Backend Flask API
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/app.py"
    plan: free
    autoDeploy: false
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: chatbot-frontend
          property: host

  # Frontend PHP Application
  - type: static
    name: chatbot-frontend
    env: static
    buildCommand: "echo 'Frontend is static, no build needed'"
    staticPublishPath: ./frontend
    plan: free
    autoDeploy: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://chatbot-backend.onrender.com/$1
